import { StyleSheet } from 'react-native';

const colors = {
  background: '#FAFBFA',
  border: '#DDE5EA',
  danger: '#E91745',
  navy: '#101935',
  primary: '#0A9E56',
  primarySoft: '#F3FBF7',
  slate: '#4B536A',
  surface: '#FFFFFF',
  warning: '#EB961C',
};

export const mobileUi = StyleSheet.create({
  actionLabel: {
    color: colors.navy,
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
  },
  actionRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 13,
  },
  activeBranchRow: {
    backgroundColor: colors.primarySoft,
  },
  activeBranchText: {
    color: colors.primary,
    fontWeight: '800',
  },
  activeChannelPill: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  activeChannelText: {
    color: colors.surface,
  },
  activeStatusTab: {
    borderBottomColor: colors.primary,
    borderBottomWidth: 2,
    color: colors.primary,
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    paddingBottom: 12,
    textAlign: 'center',
  },
  activeTabText: {
    color: colors.primary,
  },
  addButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    color: colors.primary,
    fontSize: 26,
    height: 52,
    lineHeight: 48,
    textAlign: 'center',
    width: 52,
  },
  alertIcon: {
    alignItems: 'center',
    backgroundColor: '#FDECEF',
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  alertIconText: {
    color: colors.danger,
    fontSize: 22,
    fontWeight: '900',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#F1E4D8',
    borderRadius: 999,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  avatarText: {
    color: colors.navy,
    fontSize: 13,
    fontWeight: '800',
  },
  backText: {
    color: colors.navy,
    fontSize: 42,
    lineHeight: 42,
  },
  bottomNav: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'space-between',
    marginBottom: 6,
    marginHorizontal: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: colors.navy,
    shadowOpacity: 0.12,
    shadowRadius: 20,
  },
  branchMenu: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    padding: 8,
    position: 'absolute',
    right: 0,
    shadowColor: colors.navy,
    shadowOpacity: 0.14,
    shadowRadius: 20,
    top: 52,
    width: 230,
    zIndex: 20,
  },
  branchRow: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  branchText: {
    color: colors.navy,
    fontSize: 14,
    fontWeight: '600',
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    shadowColor: colors.navy,
    shadowOpacity: 0.04,
    shadowRadius: 8,
  },
  cardDescription: {
    color: colors.slate,
    fontSize: 14,
    lineHeight: 20,
  },
  cardTitle: {
    color: colors.navy,
    fontSize: 17,
    fontWeight: '800',
  },
  centerAction: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: 999,
    borderWidth: 5,
    height: 66,
    justifyContent: 'center',
    marginTop: -34,
    shadowColor: colors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    width: 66,
  },
  centerActionText: {
    color: colors.surface,
    fontSize: 30,
    fontWeight: '800',
  },
  centerSwitcher: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
  },
  channelPill: {
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  channelRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  channelText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: '700',
  },
  chatButton: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  chatButtonText: {
    fontSize: 18,
  },
  chevron: {
    color: colors.navy,
    fontSize: 16,
    fontWeight: '900',
  },
  content: {
    gap: 16,
    paddingBottom: 14,
    paddingTop: 24,
  },
  copiCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 16,
    padding: 16,
  },
  copiHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
  },
  copiWelcome: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 18,
    padding: 16,
  },
  copilotBubble: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 10,
    maxWidth: '86%',
    padding: 12,
  },
  customerAvatar: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  customerAvatarText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    lineHeight: 20,
  },
  filterButton: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    color: colors.navy,
    fontSize: 20,
    height: 48,
    lineHeight: 46,
    textAlign: 'center',
    width: 48,
  },
  flex: {
    flex: 1,
  },
  greeting: {
    color: colors.navy,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    position: 'relative',
    zIndex: 30,
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  headerIcon: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    position: 'relative',
    width: 38,
  },
  headerIconText: {
    color: colors.navy,
    fontSize: 19,
    fontWeight: '800',
  },
  iconTile: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 14,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  iconTileSmall: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 12,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  iconTileText: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: '800',
  },
  inventoryCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  leadBadge: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  listDescription: {
    color: colors.slate,
    fontSize: 13,
    lineHeight: 18,
  },
  listRow: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  listTitle: {
    color: colors.navy,
    fontSize: 15,
    fontWeight: '800',
  },
  logo: {
    color: colors.navy,
    fontSize: 28,
    fontWeight: '300',
    letterSpacing: 7,
  },
  logoTagline: {
    color: colors.slate,
    fontSize: 11,
    marginTop: -2,
  },
  messageBubble: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    maxWidth: '80%',
    padding: 12,
  },
  messageText: {
    color: colors.navy,
    fontSize: 15,
    lineHeight: 22,
  },
  messageTime: {
    color: colors.slate,
    fontSize: 11,
    marginTop: 4,
    textAlign: 'right',
  },
  metricGrid: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 14,
  },
  metricGreen: {
    color: colors.primary,
  },
  metricItem: {
    flex: 1,
  },
  metricLabel: {
    color: colors.slate,
    fontSize: 11,
    lineHeight: 16,
  },
  metricOrange: {
    color: colors.warning,
  },
  metricRed: {
    color: colors.danger,
  },
  metricValue: {
    fontSize: 21,
    fontWeight: '900',
  },
  micButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  micButtonText: {
    color: colors.surface,
    fontSize: 24,
  },
  noteText: {
    backgroundColor: colors.primarySoft,
    borderRadius: 16,
    color: colors.slate,
    fontSize: 13,
    lineHeight: 18,
    padding: 12,
  },
  outboundMessageBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#DDFBE7',
    borderColor: '#C4F2D2',
  },
  ownerCopilotBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#DDFBE7',
    borderColor: '#C4F2D2',
  },
  primaryText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  profileAvatar: {
    alignItems: 'center',
    backgroundColor: '#F1E4D8',
    borderRadius: 999,
    height: 112,
    justifyContent: 'center',
    width: 112,
  },
  profileAvatarText: {
    color: colors.navy,
    fontSize: 28,
    fontWeight: '900',
  },
  profileCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 20,
    padding: 18,
  },
  profileLine: {
    color: colors.navy,
    fontSize: 13,
    lineHeight: 22,
  },
  profileName: {
    color: colors.navy,
    fontSize: 23,
    fontWeight: '900',
  },
  quickAction: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 12,
  },
  quickActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  quickActionText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: '800',
  },
  replyBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  replyInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    color: colors.navy,
    flex: 1,
    fontSize: 15,
    paddingHorizontal: 18,
    paddingVertical: 13,
  },
  robot: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 24,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  robotEyes: {
    color: '#7EF7C8',
    fontSize: 18,
    letterSpacing: 4,
  },
  robotFace: {
    alignItems: 'center',
    backgroundColor: colors.navy,
    borderRadius: 16,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  rowMeta: {
    alignItems: 'flex-end',
    gap: 4,
  },
  screenTitle: {
    color: colors.navy,
    fontSize: 31,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  searchInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    color: colors.slate,
    flex: 1,
    fontSize: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 10,
  },
  sectionAction: {
    color: colors.slate,
    fontSize: 13,
    fontWeight: '700',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: colors.navy,
    fontSize: 16,
    fontWeight: '900',
  },
  shell: {
    backgroundColor: colors.background,
    flex: 1,
    gap: 8,
    paddingBottom: 4,
    paddingHorizontal: 18,
  },
  signOutRow: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  signOutText: {
    color: colors.danger,
    fontSize: 15,
    fontWeight: '800',
  },
  statusTab: {
    color: colors.slate,
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    paddingBottom: 12,
    textAlign: 'center',
  },
  statusTabs: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    marginBottom: 4,
  },
  subheading: {
    color: colors.slate,
    fontSize: 15,
    lineHeight: 22,
    marginTop: -8,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    gap: 2,
  },
  tabIcon: {
    color: colors.slate,
    fontSize: 18,
  },
  tabLabel: {
    color: colors.slate,
    fontSize: 11,
    fontWeight: '700',
  },
  threadCard: {
    backgroundColor: '#FBFCFB',
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
  },
  threadHeader: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  timestamp: {
    color: colors.slate,
    fontSize: 12,
  },
  unreadBadge: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    color: colors.surface,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  unreadDot: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 7,
    position: 'absolute',
    right: 5,
    top: 4,
    width: 7,
  },
});
