import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsObject, IsOptional, IsString, MinLength } from 'class-validator';

export class HealthResponseDto {
  @ApiProperty({ enum: ['ok'], example: 'ok' })
  status!: 'ok';
}

export class ErrorResponseDto {
  @ApiProperty({ example: 401 })
  statusCode!: number;

  @ApiProperty({ example: 'Unauthorized' })
  message!: string | string[];

  @ApiPropertyOptional({ example: 'Unauthorized' })
  error?: string;
}

export class ApproveDraftRequestDto {
  @ApiPropertyOptional({
    description: 'Optional owner-edited message body. When omitted, the original AI draft body is sent.',
    example: '¡Hola! Sí, tenemos stock disponible. ¿Querés que te reserve uno?',
  })
  body?: string;
}

export class DraftSentResponseDto {
  @ApiProperty({ enum: ['sent'], example: 'sent' })
  status!: 'sent';
}

export class DraftRejectedResponseDto {
  @ApiProperty({ enum: ['rejected'], example: 'rejected' })
  status!: 'rejected';
}

export class CopilotQuestionRequestDto {
  @ApiProperty({
    description: 'Organization UUID whose business data should be queried.',
    example: '4e6f8a6f-9b6e-4f7f-8c1e-0f9f7c8d9a12',
  })
  @IsString()
  organizationId!: string;

  @ApiPropertyOptional({
    description: 'Business center UUID. Defaults to the organization default center.',
  })
  @IsOptional()
  @IsString()
  businessCenterId?: string;

  @ApiPropertyOptional({
    description: 'Existing Copi session UUID to continue a conversation.',
  })
  @IsOptional()
  @IsString()
  sessionId?: string;

  @ApiProperty({
    description: 'Owner question for Copi.',
    example: '¿Qué clientes necesitan seguimiento hoy?',
  })
  @IsString()
  @MinLength(1)
  question!: string;

  @ApiPropertyOptional({
    description:
      'Optional vision analysis context. Used for reasoning but not stored as the owner chat bubble.',
  })
  @IsOptional()
  @IsString()
  imageContext?: string;
}

export class OwnerCopilotResponseDto {
  @ApiProperty({
    description: 'Natural-language answer generated by Copi.',
    example: 'Tenés 7 seguimientos pendientes. Te conviene empezar por María González.',
  })
  answer!: string;

  @ApiProperty({ description: 'Server-side response time in milliseconds.', example: 42 })
  responseTimeMs!: number;

  @ApiProperty({ description: 'Copi session UUID.', example: '4e6f8a6f-9b6e-4f7f-8c1e-0f9f7c8d9a12' })
  sessionId!: string;

  @ApiProperty({ enum: ['basic', 'pro'], example: 'basic' })
  tier!: 'basic' | 'pro';

  @ApiProperty({ enum: ['allowed', 'policy_denied', 'tier_required'], example: 'allowed' })
  policyDecision!: 'allowed' | 'policy_denied' | 'tier_required';

  @ApiProperty({
    description: 'Internal tools used to answer the question.',
    example: ['attention_summary'],
    isArray: true,
  })
  tools!: string[];

  @ApiPropertyOptional({ description: 'Proposed write action awaiting confirmation.' })
  proposedAction?: Record<string, unknown> | null;

  @ApiPropertyOptional({ description: 'Token usage for LLM phrasing.' })
  tokenUsage?: { inputTokens: number; outputTokens: number };
}

export class CopiActionConfirmRequestDto {
  @ApiProperty()
  @IsString()
  organizationId!: string;

  @ApiProperty()
  @IsString()
  businessCenterId!: string;
}

export class CopiVoiceRequestDto {
  @ApiProperty()
  @IsString()
  organizationId!: string;

  @ApiProperty()
  @IsString()
  @MinLength(1)
  audioBase64!: string;

  @ApiProperty({ example: 'audio/webm' })
  @IsString()
  mimeType!: string;
}

export class CopiVisionRequestDto {
  @ApiProperty()
  @IsString()
  organizationId!: string;

  @ApiProperty()
  @IsString()
  @MinLength(1)
  imageBase64!: string;

  @ApiProperty({ example: 'image/jpeg' })
  @IsString()
  mimeType!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  prompt?: string;
}

export class CopiReportRunRequestDto {
  @ApiProperty()
  @IsString()
  organizationId!: string;

  @ApiProperty()
  @IsString()
  businessCenterId!: string;

  @ApiProperty({ example: 'sales_last_7_days' })
  @IsString()
  reportKey!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsObject()
  parameters?: Record<string, unknown>;
}

export class TaskMaintenanceResultDto {
  @ApiProperty({ example: 3 })
  followUpTasksCreated!: number;

  @ApiProperty({ example: 2 })
  lowStockAlertsCreated!: number;

  @ApiProperty({ example: 4 })
  pushNotificationsSent!: number;

  @ApiProperty({ example: 0 })
  pushNotificationsFailed!: number;
}

export class WhatsAppWebhookResponseDto {
  @ApiProperty({ example: true })
  received!: true;

  @ApiProperty({ example: 1 })
  eventCount!: number;
}

export class WhatsAppMessageTextDto {
  @ApiPropertyOptional({ example: 'Hola, ¿tienen stock?' })
  body?: string;
}

export class WhatsAppWebhookMessageDto {
  @ApiPropertyOptional({ example: 'wamid.HBgN...' })
  id?: string;

  @ApiPropertyOptional({ example: '5491112345678' })
  from?: string;

  @ApiPropertyOptional({ example: '1717790400' })
  timestamp?: string;

  @ApiPropertyOptional({ example: 'text' })
  type?: string;

  @ApiPropertyOptional({ type: WhatsAppMessageTextDto })
  text?: WhatsAppMessageTextDto;
}

export class WhatsAppContactProfileDto {
  @ApiPropertyOptional({ example: 'María González' })
  name?: string;
}

export class WhatsAppContactDto {
  @ApiPropertyOptional({ example: '5491112345678' })
  wa_id?: string;

  @ApiPropertyOptional({ type: WhatsAppContactProfileDto })
  profile?: WhatsAppContactProfileDto;
}

export class WhatsAppMetadataDto {
  @ApiPropertyOptional({ example: '5491123456789' })
  display_phone_number?: string;

  @ApiPropertyOptional({ example: '123456789012345' })
  phone_number_id?: string;
}

export class WhatsAppWebhookChangeValueDto {
  @ApiPropertyOptional({ example: 'whatsapp' })
  messaging_product?: string;

  @ApiPropertyOptional({ type: WhatsAppMetadataDto })
  metadata?: WhatsAppMetadataDto;

  @ApiPropertyOptional({ type: WhatsAppContactDto, isArray: true })
  contacts?: WhatsAppContactDto[];

  @ApiPropertyOptional({ type: WhatsAppWebhookMessageDto, isArray: true })
  messages?: WhatsAppWebhookMessageDto[];
}

export class WhatsAppWebhookChangeDto {
  @ApiPropertyOptional({ example: 'messages' })
  field?: string;

  @ApiPropertyOptional({ type: WhatsAppWebhookChangeValueDto })
  value?: WhatsAppWebhookChangeValueDto;
}

export class WhatsAppWebhookEntryDto {
  @ApiPropertyOptional({ example: '123456789012345' })
  id?: string;

  @ApiPropertyOptional({ type: WhatsAppWebhookChangeDto, isArray: true })
  changes?: WhatsAppWebhookChangeDto[];
}

export class WhatsAppWebhookPayloadDto {
  @ApiPropertyOptional({ example: 'whatsapp_business_account' })
  object?: string;

  @ApiPropertyOptional({ type: WhatsAppWebhookEntryDto, isArray: true })
  entry?: WhatsAppWebhookEntryDto[];
}

export class WhatsAppOtpRequestDto {
  @ApiProperty({ example: '+5491112345678' })
  @IsString()
  @MinLength(8)
  phone!: string;
}

export class WhatsAppOtpVerifyDto {
  @ApiProperty({ example: '+5491112345678' })
  @IsString()
  @MinLength(8)
  phone!: string;

  @ApiProperty({ example: '123456' })
  @IsString()
  @MinLength(4)
  code!: string;
}

export class AcceptOrganizationInviteDto {
  @ApiProperty()
  @IsString()
  @MinLength(8)
  inviteToken!: string;

  @ApiPropertyOptional({
    description: 'Ignored as auth evidence; phone is taken from the authenticated Supabase user.',
    example: '+5491112345678',
  })
  @IsOptional()
  @IsString()
  verifiedPhoneE164?: string;
}

export class InstagramOAuthStartDto {
  @ApiProperty({ format: 'uuid' })
  @IsString()
  organizationId!: string;
}

export class InstagramOAuthStartResponseDto {
  @ApiProperty({ example: 'https://www.instagram.com/oauth/authorize?...' })
  authUrl!: string;

  @ApiProperty({ description: 'Signed state returned to oauth/callback' })
  state!: string;
}

export class InstagramOAuthCallbackDto {
  @ApiProperty()
  @IsString()
  code!: string;

  @ApiProperty()
  @IsString()
  state!: string;
}

export class InstagramConnectionSummaryDto {
  @ApiPropertyOptional({ nullable: true })
  igUserId!: string | null;

  @ApiPropertyOptional({ nullable: true })
  igUsername!: string | null;

  @ApiPropertyOptional({ nullable: true })
  lastError!: string | null;

  @ApiPropertyOptional({ nullable: true })
  lastStatusCheckAt!: string | null;

  @ApiPropertyOptional({ nullable: true })
  pageId!: string | null;

  @ApiPropertyOptional({ nullable: true })
  profilePictureUrl?: string | null;

  @ApiProperty({
    enum: ['not_configured', 'pending', 'connected', 'error', 'disabled'],
  })
  status!: 'not_configured' | 'pending' | 'connected' | 'error' | 'disabled';

  @ApiPropertyOptional({ nullable: true })
  tokenExpiresAt?: string | null;

  @ApiPropertyOptional({ nullable: true })
  verifiedAt!: string | null;
}

export class InstagramDisconnectDto {
  @ApiProperty({ format: 'uuid' })
  @IsString()
  organizationId!: string;
}

export class InstagramMessagingWindowStateDto {
  @ApiProperty({
    enum: [
      'customer_must_message_first',
      'reply_available',
      'human_reply_only',
      'window_expired',
      'meta_approval_required',
    ],
  })
  state!: string;

  @ApiPropertyOptional({ nullable: true })
  expiresAt!: string | null;

  @ApiPropertyOptional({ nullable: true })
  lastInboundAt!: string | null;
}

export class InstagramSendMessageDto {
  @ApiProperty()
  @IsString()
  @MinLength(1)
  body!: string;

  @ApiProperty({ format: 'uuid' })
  @IsString()
  businessCenterId!: string;

  @ApiProperty({ format: 'uuid' })
  @IsString()
  conversationId!: string;

  @ApiProperty({ format: 'uuid' })
  @IsString()
  organizationId!: string;
}

export class InstagramSendMessageResponseDto {
  @ApiPropertyOptional({ nullable: true })
  externalMessageId!: string | null;

  @ApiProperty({ enum: ['sent'] })
  status!: 'sent';
}
